I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script call
    call harbouring
  File "game/Harbouring.rpy", line 107, in script
    scene bg docks night with fade
Exception: Image 'bg docks' does not accept attributes 'night'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script call
    call harbouring
  File "game/Harbouring.rpy", line 107, in script
    scene bg docks night with fade
  File "C:\Users\nicky\Downloads\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\ast.py", line 1251, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\nicky\Downloads\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\ast.py", line 1080, in show_imspec
    renpy.config.show(name,
  File "C:\Users\nicky\Downloads\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\nicky\Downloads\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\nicky\Downloads\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Users\nicky\Downloads\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'bg docks' does not accept attributes 'night'.

Windows-10-10.0.22000 AMD64
Ren'Py 8.3.4.24120703
Harbouring Feelings 1.0
Thu Feb 20 14:29:26 2025
